trigger:
  branches:
    include:
      - initial
      - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Gradle@2
    displayName: Build and test
    inputs:
      options: '--info'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      tasks: build jacocoTestReport

  - task: PublishCodeCoverageResults@1
    displayName: "Publish coverage (Azure)"
    inputs:
      codeCoverageTool: 'JaCoCo' # Options: cobertura, jaCoCo
      summaryFileLocation: "$(System.DefaultWorkingDirectory)/sdk-standalone/build/reports/jacoco/test/jacocoTestReport.xml"
      failIfCoverageEmpty: true
      reportDirectory: "$(System.DefaultWorkingDirectory)/sdk-standalone/build/reports/jacoco/test/html/"

  - bash: >
      bash <(curl -s https://codecov.io/bash)
    env:
      CODECOV_TOKEN: $(CODECOV_TOKEN)
    displayName: "Publish coverage (Codecov)"


